import { Pattern } from "@/types";

export const ExcisionV2: Pattern = [
  {
    beads: [
      { x: 0, y: 0, color: "gray" },
      { x: 2, y: 0, color: "gray" },
      { x: 4, y: -2, color: "gray" },
      { x: 6, y: -4, color: "gray" },
      { x: 8, y: -2, color: "gray" },
      { x: 10, y: 0, color: "gray" },
      { x: 12, y: 0, color: "gray" },
      { x: 12, y: -2, color: "gray" },
      { x: 12, y: -4, color: "gray" },
      { x: 10, y: -6, color: "gray" },
      { x: 8, y: -8, color: "gray" },
      { x: 10, y: -10, color: "gray" },
      { x: 12, y: -12, color: "gray" },
      { x: 12, y: -14, color: "gray" },
      { x: 12, y: -16, color: "gray" },
      { x: 10, y: -18, color: "gray" },
      { x: 8, y: -20, color: "gray" },
      { x: 8, y: -18, color: "gray" },
      { x: 8, y: -16, color: "gray" },
      { x: 8, y: -14, color: "gray" },
      { x: 6, y: -12, color: "gray" },
      { x: 4, y: -14, color: "gray" },
      { x: 4, y: -16, color: "gray" },
      { x: 4, y: -18, color: "gray" },
      { x: 4, y: -20, color: "gray" },
      { x: 4, y: -22, color: "gray" },
      { x: 2, y: -20, color: "gray" },
      { x: 0, y: -18, color: "gray" },
      { x: 0, y: -16, color: "gray" },
      { x: 0, y: -14, color: "gray" },
      { x: 0, y: -12, color: "gray" },
      { x: 2, y: -10, color: "gray" },
      { x: 4, y: -8, color: "gray" },
      { x: 2, y: -6, color: "gray" },
      { x: 0, y: -4, color: "gray" },
      { x: 0, y: -2, color: "gray" },
      { x: 2, y: -2, color: "#e0b3fc" },
      { x: 4, y: -4, color: "#e0b3fc" },
      { x: 6, y: -6, color: "#e0b3fc" },
      { x: 8, y: -4, color: "#e0b3fc" },
      { x: 10, y: -2, color: "#e0b3fc" },
      { x: 10, y: -4, color: "#e0b3fc" },
      { x: 8, y: -6, color: "#e0b3fc" },
      { x: 6, y: -8, color: "#e0b3fc" },
      { x: 8, y: -10, color: "#e0b3fc" },
      { x: 10, y: -12, color: "#e0b3fc" },
      { x: 10, y: -14, color: "#e0b3fc" },
      { x: 10, y: -16, color: "#e0b3fc" },
      { x: 8, y: -12, color: "#e0b3fc" },
      { x: 6, y: -10, color: "#e0b3fc" },
      { x: 4, y: -12, color: "#e0b3fc" },
      { x: 2, y: -14, color: "#e0b3fc" },
      { x: 2, y: -16, color: "#e0b3fc" },
      { x: 2, y: -18, color: "#e0b3fc" },
      { x: 2, y: -12, color: "#e0b3fc" },
      { x: 4, y: -10, color: "#e0b3fc" },
      { x: 4, y: -6, color: "#e0b3fc" },
      { x: 2, y: -4, color: "#e0b3fc" },
    ],
  },
];
